name: Publish
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install npm dependencies
        run: yarn --frozen-lockfile
        shell: bash
      - name: Publish
        run: |
          export GH_TOKEN=${{ secrets.GH_TOKEN }}
          export NPM_TOKEN=${{ secrets.NPM_TOKEN }}
          yarn install
          yarn ci:publish
    timeout-minutes: 60
